# Generated by Django 4.0.3 on 2022-04-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrativo'), (4, 'Curador'), (5, 'Cliente')], default=5, verbose_name='Tipo usuário'),
        ),
    ]
