# Generated by Django 4.0.3 on 2022-04-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='average_to_pay',
            field=models.FloatField(help_text='Nota média nos Atendimentos, para que o Curador                    passe a ser Pago', null=True, verbose_name='Nota média para ser Pago'),
        ),
    ]
