# Generated by Django 4.0.3 on 2022-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracao_average_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticemail',
            name='text',
            field=models.TextField(help_text="Text which will be presented in the e-mail's body.<br/>Tags may be used to dynamically insert other content in the e-mail's body.<br/><br/>Tag list:<br/>- General:<br/>--- {user} (will insert an username of the client)<br/>--- {client_name} (will insert the client's full name)<br/>--- {client_email} (will insert the client's e-mail)<br/>--- {list_client_names} (will insert a list of all client names)<br/>--- {document_name} (will insert the name of the document evaluated)<br/>- Checklist Section Refused:<br/>--- {checklist_refused_section} (will insert the name of the checklist section that was refused)<br/>--- {checklist_refused_reason} (will insert the reason for checklist section being refused)<br/>- Password Changed by Admin & New Password:<br/>--- {password_token_url} (will insert the link to a form that allows the user to redefine his password)<br/>- Alerts:<br/>--- {section_label} (will insert the name of the section completed)<br/>--- {receipt_document_name} (will insert the name of the document which the client has sent a receipt of)<br/>--- {rating} (will insert the rating of the client as declared by compliance)<br/>--- {compliance_user} (will insert the name of the compliance user involved in the event, if any)<br/>--- {compliance_evaluation_reason} (will insert the reason for approval or refusal of the client as written by the compliance user)<br/>--- {document_status} (will insert the evaluation status of the document, approved or refused)<br/>--- {document_evaluation_reason} (will insert the reason for approval or refusal of the document as written by the compliance/sales user)<br/>--- {manager_section} (will insert the name of which section the client was approved/refused in by a manager)<br/>--- {manager_evaluation_reason} (will insert the reason of the approval/refusal as stated by the manager)<br/>--- {funds_value} (will insert the value in funds of the client  as inputted by the client services user)<br/>--- {funds_currency} (will insert the currency of the client as inputted by the client services user)<br/>--- {funds_info} (will insert any additional info of the client's funds as inputted by the client services user)<br/>--- {otc_pf_number} (will insert the client's OTC Portfolio Number)<br/>--- {mcm_inc_pf_number} (will insert the client's MCM Inc. Portfolio Number)<br/>--- {mcm_ltd_pf_number} (will insert the client's MCM Ltd. Portfolio Number)<br/>--- {dtvm_pf_number} (will insert the client's DTVM Portfolio Number)<br/>--- {credit_reason} (will insert the reason for approval/refusal of credit facility)<br/>--- {credit_im_value} (will insert the client's Initial Margin Credit Value)<br/>--- {credit_iv_value} (will insert the client's Variation Margin Credit Value)<br/>--- {client_desk} (will insert the desk the client has chosen to work with)<br/>--- {products_add_docs_list} (will insert the list of products/assets that the client has chosen which require additional documentation)<br/>- Additional Document Approval:<br/>--- {add_doc_product} (will insert the name of the product associated with the approved additional document)<br/>- Password Changing by Email:<br/>--- {email_password_changing_token} (will insert the token for password changing that will be sent by email to the client)<br/>- Revalidation by Email:<br/>--- {email_revalidation_token} (will insert the token for revalidation that will be sent by email to the client)<br/><br/>Please make sure the tags are correct, and in the correct type of e-mail, as they may cause the e-mail body content to be incorrect if they are not.", verbose_name='E-mail Texto'),
        ),
        migrations.AlterField(
            model_name='automaticemail',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nova Senha'), (10, 'Curador tem um novo Cliente')], default=1, help_text='Determina do tipo de e-mail  que este registro representa.', unique=True, verbose_name='Tipo de E-mail'),
        ),
    ]
