# Generated by Django 4.0.3 on 2022-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_automaticemail_text_alter_automaticemail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticemail',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nova Senha'), (10, 'Curador tem um novo Cliente'), (20, 'Curador encerrou Atendimento ao Cliente')], default=1, help_text='Determina do tipo de e-mail  que este registro representa.', unique=True, verbose_name='Tipo de E-mail'),
        ),
    ]
