# Generated by Django 4.0.3 on 2022-04-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Titulo da Especialidade')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição da Especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade de Consulta',
                'verbose_name_plural': 'Especialidades de Consultas',
            },
        ),
        migrations.CreateModel(
            name='CuradorEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curador_especialidades', to=settings.AUTH_USER_MODEL, verbose_name='Curador')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especialidade_curadores', to='curador.especialidade', verbose_name='Especialidade')),
            ],
            options={
                'verbose_name': 'Especialidade do Curador',
                'verbose_name_plural': 'Especialidades do Curador',
            },
        ),
    ]
