# Generated by Django 4.0.3 on 2022-04-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointments_to_pay', models.PositiveSmallIntegerField(help_text='Número de Atendimentos para que o Curador                    passe a ser Pago', null=True, verbose_name='Atendimentos para ser Pago')),
                ('average_to_pay', models.PositiveSmallIntegerField(help_text='Nota média nos Atendimentos, para que o Curador                    passe a ser Pago', null=True, verbose_name='Nota média para ser Pago')),
            ],
            options={
                'verbose_name': 'Config do Curador',
                'verbose_name_plural': 'Config do Curador',
            },
        ),
    ]
