# Generated by Django 4.0.3 on 2022-04-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curador', '0002_configuracao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracao',
        ),
    ]
