# Generated by Django 3.2.10 on 2022-04-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curador', '0003_delete_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuradorAboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(null=True, verbose_name='About me text')),
                ('curador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Curador')),
            ],
            options={
                'verbose_name': 'Curador About me',
            },
        ),
    ]
