# Generated by Django 3.2.10 on 2022-04-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curador', '0004_curadoraboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='curadoraboutme',
            name='titulo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Title About Me'),
        ),
    ]
