# Generated by Django 4.0.3 on 2022-04-13 16:58

from django.db import migrations, models
import site_setup.tools_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente')),
                ('document_id', models.CharField(blank=True, help_text='Documento que identifica exclusivamente o Contratante', max_length=30, null=True, verbose_name='CNPJ/CPF/TAX ID')),
                ('endereco', models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço completo')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente Contratante',
                'verbose_name_plural': 'Cliente Contratante',
            },
        ),
        migrations.CreateModel(
            name='ClienteMinicomSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, help_text='Código interno gerado ao habilitar o contratante do sistema.                    Copiado ClienteContratante.Codigo_id', max_length=30, null=True, verbose_name='Identificação do Contratante')),
                ('data_setup', models.DateField(blank=True, null=True, verbose_name='Data Setup')),
                ('last_check', models.DateField(help_text='Determina se o site está em dia e habilitado a funcionar', verbose_name='Última Checagem')),
            ],
            options={
                'verbose_name': 'Cliente Setup',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=site_setup.tools_models.site_logo_path, verbose_name='Imagem do Logo da Instituição')),
                ('logo_company_image', models.ImageField(blank=True, help_text='Imagem transparente, logo da empresa, que aparece,             por exemplo, na tela de login, do lado direito, ao alto,             sobre a bg_general_image. Transparente.', null=True, upload_to=site_setup.tools_models.site_logo_path, verbose_name='Company logo ')),
                ('logo_book', models.ImageField(blank=True, null=True, upload_to=site_setup.tools_models.site_logo_path, verbose_name='Imagem do Logo da Instituição no Book')),
                ('bg_general_image', models.ImageField(blank=True, help_text='Imagem que aparece em background em várias partes do site', null=True, upload_to=site_setup.tools_models.site_background_path, verbose_name='Imagem Geral de Background')),
                ('bg_landing_image', models.ImageField(blank=True, null=True, upload_to=site_setup.tools_models.site_background_path, verbose_name='Imagem Background Landing Page')),
                ('favicon_image', models.ImageField(blank=True, help_text='Imagem que aparece em todas as telas. Icone da empresa', null=True, upload_to=site_setup.tools_models.site_favicon_path, verbose_name='Imagem do icon favorito')),
                ('css_file', models.FileField(blank=True, null=True, upload_to=site_setup.tools_models.site_css_path, verbose_name='Arquivo com o CSS')),
            ],
            options={
                'verbose_name': 'Configurações Gerais do Site',
                'verbose_name_plural': 'Configurações Gerais do Site',
            },
        ),
        migrations.CreateModel(
            name='TextoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('pt-br', 'PORTUGUES'), ('en', 'INGLES')], default='pt-br', max_length=5, unique=True, verbose_name='Linguagem do texto')),
                ('landing_page_wellcome_phrase', models.CharField(blank=True, max_length=256, null=True, verbose_name='Página de Entrada. Boas Vindas em uma Frase')),
                ('landing_page_wellcome_text', models.TextField(blank=True, null=True, verbose_name='Página de Entrada. Boas Vindas em um Texto')),
                ('landing_page_join_us', models.CharField(blank=True, max_length=128, null=True, verbose_name='Mensagem para "Junte-se a nós"')),
                ('login_wellcome', models.CharField(blank=True, max_length=256, null=True, verbose_name='Página de login. Boas Vindas')),
                ('login_wellcome_msg', models.TextField(blank=True, null=True, verbose_name='Página de login. Mensagem')),
            ],
            options={
                'verbose_name': 'Texto Site',
                'verbose_name_plural': 'Textos do Site',
            },
        ),
    ]
