# Generated by Django 4.0.3 on 2022-04-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteMinicomSetup',
            new_name='ClienteSetup',
        ),
    ]
