# Generated by Django 4.0.3 on 2022-04-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_cliente', models.SmallIntegerField(choices=[(1, 'Não Gostei.'), (2, 'Achei muito fraco.'), (3, 'Razoável, ajudou pouca coisa.'), (4, 'Achei bom, aprendi coisas importantes.'), (5, 'Atendimento Ótimo! Transformador!')], null=True, verbose_name='Avaliação do Cliente')),
                ('depoimento_cliente', models.TextField(blank=True, null=True, verbose_name='Depoimento do Cliente')),
                ('data_agendamento', models.DateField(auto_now_add=True, help_text='(DD/MM/AAAA)', verbose_name='Data do Agendamento')),
                ('status_agendamento', models.SmallIntegerField(choices=[(0, 'Agendamento Aberto'), (1, 'Agendamento Encerrado')], default=0, verbose_name='Status do Agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('curador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_curador', to='curador.curadorespecialidade', verbose_name='Curador')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
