# Generated by Django 4.0.3 on 2022-04-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='avaliacao_cliente',
            field=models.SmallIntegerField(choices=[(0, 'Pendente.'), (1, 'Não Gostei.'), (2, 'Achei muito fraco.'), (3, 'Razoável, ajudou pouca coisa.'), (4, 'Achei bom, aprendi coisas importantes.'), (5, 'Atendimento Ótimo! Transformador!')], default=0, verbose_name='Avaliação do Cliente'),
        ),
    ]
