# Generated by Django 4.0.3 on 2022-04-11 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curador', '0002_configuracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0002_alter_atendimento_avaliacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='especialidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_especialidade', to='curador.especialidade', verbose_name='Especialidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='curador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_curador', to=settings.AUTH_USER_MODEL, verbose_name='Curador'),
        ),
    ]
