# Generated by Django 4.0.3 on 2022-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_atendimento_especialidade_alter_atendimento_curador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_depoimento',
            field=models.DateField(blank=True, help_text='(DD/MM/AAAA)', null=True, verbose_name='Data do Depoimento'),
        ),
    ]
