# Generated by Django 4.0.3 on 2022-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_remove_atendimento_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='anotacoes_ccurador',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações do Curador para acompanhamento'),
        ),
    ]
