# Generated by Django 4.0.3 on 2022-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_rename_anotacoes_ccurador_atendimento_anotacoes_curador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_encerramento',
            field=models.DateField(blank=True, help_text='(DD/MM/AAAA)', null=True, verbose_name='Data do Enceramento'),
        ),
    ]
