# Generated by Django 4.0.3 on 2022-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_atendimento_data_encerramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='is_depoimento_moderado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Depoimento está moderado?'),
        ),
    ]
